import type { Metadata } from 'next'
import './globals.css'
import { Poppins , Whisper , Shadows_Into_Light } from 'next/font/google';


const whisper =  Whisper({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-whisper',
  weight: [ '400']
})
const shadows_Into_Light =  Shadows_Into_Light({
  subsets: ['latin'],
  display: 'swap',
  variable: '--shadows_Into_Light',
  weight: [ '400']
})

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${shadows_Into_Light.variable} ${whisper.variable}`} >
      <body>{children}</body>
    </html>
  )
}
